# Generated by Django 5.2.8 on 2026-01-29 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BSC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categorias', models.ManyToManyField(blank=True, related_name='bscs', to='api.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('indicador', models.CharField(blank=True, max_length=255, null=True)),
                ('dueno', models.CharField(blank=True, max_length=255, null=True)),
                ('unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_de_indicador', models.CharField(blank=True, max_length=255, null=True)),
                ('condicion', models.CharField(blank=True, choices=[('MAYOR', 'Mayor'), ('MENOR', 'Menor')], default='MAYOR', max_length=10, null=True)),
                ('ano_a_la_fecha', models.FloatField(blank=True, null=True)),
                ('metodo_q', models.CharField(blank=True, choices=[('PROMEDIO', 'Promedio'), ('SUMA', 'Suma')], default='PROMEDIO', max_length=10, null=True)),
                ('ene_r', models.FloatField(blank=True, null=True)),
                ('feb_r', models.FloatField(blank=True, null=True)),
                ('mar_r', models.FloatField(blank=True, null=True)),
                ('abr_r', models.FloatField(blank=True, null=True)),
                ('may_r', models.FloatField(blank=True, null=True)),
                ('jun_r', models.FloatField(blank=True, null=True)),
                ('jul_r', models.FloatField(blank=True, null=True)),
                ('ago_r', models.FloatField(blank=True, null=True)),
                ('sep_r', models.FloatField(blank=True, null=True)),
                ('oct_r', models.FloatField(blank=True, null=True)),
                ('nov_r', models.FloatField(blank=True, null=True)),
                ('dic_r', models.FloatField(blank=True, null=True)),
                ('q1_r', models.FloatField(blank=True, null=True)),
                ('q2_r', models.FloatField(blank=True, null=True)),
                ('q3_r', models.FloatField(blank=True, null=True)),
                ('q4_r', models.FloatField(blank=True, null=True)),
                ('ene_o', models.FloatField(blank=True, null=True)),
                ('feb_o', models.FloatField(blank=True, null=True)),
                ('mar_o', models.FloatField(blank=True, null=True)),
                ('abr_o', models.FloatField(blank=True, null=True)),
                ('may_o', models.FloatField(blank=True, null=True)),
                ('jun_o', models.FloatField(blank=True, null=True)),
                ('jul_o', models.FloatField(blank=True, null=True)),
                ('ago_o', models.FloatField(blank=True, null=True)),
                ('sep_o', models.FloatField(blank=True, null=True)),
                ('oct_o', models.FloatField(blank=True, null=True)),
                ('nov_o', models.FloatField(blank=True, null=True)),
                ('dic_o', models.FloatField(blank=True, null=True)),
                ('q1_o', models.FloatField(blank=True, null=True)),
                ('q2_o', models.FloatField(blank=True, null=True)),
                ('q3_o', models.FloatField(blank=True, null=True)),
                ('q4_o', models.FloatField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categorias', models.ManyToManyField(blank=True, related_name='indicadores', to='api.categoria')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=150)),
                ('apellidos', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodigoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('usado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='codigo_registro', to='api.persona')),
            ],
        ),
        migrations.CreateModel(
            name='IndicadorRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='padres', to='api.indicador')),
                ('indicador_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='api.indicador')),
            ],
            options={
                'unique_together': {('indicador_padre', 'indicador_hijo')},
            },
        ),
    ]
